# Generated by Django 3.1 on 2021-01-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='images/pic01.jpg', null=True, upload_to='categories'),
        ),
    ]
